



site_geo = {
     'Aberdeen': ['57.157360', '-2.094278'],
      'Aberdeen Union Street Roadside': ['57.144555', '-2.106472'],
      'Aberdeen Wellington Road': ['57.133888', '-2.094198'],
      'Armagh Roadside': ['54.353728', '-6.654558'],
      'Aston Hill': ['52.503850', '-3.034178'],
      'Auchencorth Moss': ['55.792160', '-3.242900'],
      'Barnsley Gawber': ['53.562920', '-1.510436'],
      'Barnstaple A39': ['51.074793', '-4.041924'],
      'Bath Roadside': ['51.391127', '-2.354155'],
      'Belfast Centre': ['54.599650', '-5.928833'],
      "Belfast Stockman's Lane": ['54.572586', '-5.974944'],
      'Birkenhead Borough Road': ['53.388511', '-3.025014'],
      'Birmingham A4540 Roadside': ['52.476090', '-1.875024'],
      'Birmingham Acocks Green': ['52.437165', '-1.829999'],
      'Blackpool Marton': ['53.804890', '-3.007175'],
      'Bournemouth': ['50.739570', '-1.826744'],
      'Bradford Mayo Avenue': ['53.771245', '-1.759774'],
      'Brighton Preston Park': ['50.840836', '-0.147572'],
      "Bristol St Paul's": ['51.462839', '-2.584482'],
      'Bristol Temple Way': ['51.457968', '-2.583975'],
      'Bury Whitefield Roadside': ['53.559029', '-2.293772'],
      'Cambridge Roadside': ['52.202370', '0.124456'],
      'Camden Kerbside': ['51.544210', '-0.175269'],
      'Cannock A5190 Roadside': ['52.687298', '-1.980821'],
      'Canterbury': ['51.273990', '1.098061'],
      'Cardiff Centre': ['51.481780', '-3.176250'],
      'Carlisle Roadside': ['54.894834', '-2.945307'],
      'Charlton Mackrell': ['51.056250', '-2.683450'],
      'Chatham Roadside': ['51.374264', '0.547970'],
      'Chepstow A48': ['51.638094', '-2.678731'],
      'Chesterfield Loundsley Green': ['53.244131', '-1.454946'],
      'Chesterfield Roadside': ['53.231722', '-1.456944'],
      'Chilbolton Observatory': ['51.149617', '-1.438228'],
      'Christchurch Barrack Road': ['50.735454', '-1.780888'],
      'Coventry Allesley': ['52.411563', '-1.560228'],
      'Coventry Binley Road.': ['52.407708', '-1.490082'],
      'Cwmbran': ['51.653800', '-3.006953'],
      "Derby St Alkmund's Way": ['52.922983', '-1.469507'],
      'Doncaster A630 Cleveland Street': ['53.518868', '-1.138073'],
      'Eastbourne': ['50.805778', '0.271611'],
      'Edinburgh St Leonards': ['55.945589', '-3.182186'],
      'Eskdalemuir': ['55.315310', '-3.206111'],
      'Exeter Roadside': ['50.725083', '-3.532465'],
      'Fort William': ['56.822660', '-5.101102'],
      'Glasgow High Street': ['55.860936', '-4.238214'],
      'Glazebury': ['53.460080', '-2.472056'],
      'Grangemouth': ['56.010319', '-3.704399'],
      'Grangemouth Moray': ['56.013142', '-3.710833'],
      'High Muffles': ['54.334944', '-0.808550'],
      'Horley': ['51.165865', '-0.167734'],
      'Hull Freetown': ['53.748780', '-0.341222'],
      'Hull Holderness Road': ['53.758971', '-0.305749'],
      'Inverness': ['57.481308', '-4.241451'],
      'Ladybower': ['53.403370', '-1.752006'],
      'Leamington Spa': ['52.288810', '-1.533119'],
      'Leamington Spa Rugby Road': ['52.294884', '-1.542911'],
      'Leeds Centre': ['53.803780', '-1.546472'],
      'Leeds Headingley Kerbside': ['53.819972', '-1.576361'],
      'Leicester A594 Roadside': ['52.638677', '-1.124228'],
      'Leicester University': ['52.619823', '-1.127311'],
      'Leominster': ['52.221740', '-2.736665'],
      'Liverpool Speke': ['53.346330', '-2.844333'],
      'London Bexley': ['51.466030', '0.184806'],
      'London Bloomsbury': ['51.522290', '-0.125889'],
      'London Eltham': ['51.452580', '0.070766'],
      'London Harlington': ['51.488790', '-0.441614'],
      'London Marylebone Road': ['51.522530', '-0.154611'],
      'London N. Kensington': ['51.521050', '-0.213492'],
      'London Westminster': ['51.494670', '-0.131931'],
      'Lullington Heath': ['50.793700', '0.181250'],
      'Luton A505 Roadside': ['51.892293', '-0.462110'],
      'Manchester Piccadilly': ['53.481520', '-2.237881'],
      'Manchester Sharston': ['53.371306', '-2.239218'],
      'Middlesbrough': ['54.569297', '-1.220874'],
      'Narberth': ['Easting/Northing: 214440', '212663'],
      'Newcastle Centre': ['54.978250', '-1.610528'],
      'Newport': ['51.601203', '-2.977281'],
      'Norwich Lakenfields': ['52.614193', '1.301976'],
      'Nottingham Centre': ['52.954730', '-1.146447'],
      'Nottingham Western Boulevard': ['52.969377', '-1.188851'],
      'Oldbury Birmingham Road': ['52.502436', '-2.003497'],
      'Oxford Centre Roadside': ['51.751745', '-1.257463'],
      'Oxford St Ebbes': ['51.744806', '-1.260278'],
      'Peebles': ['55.657472', '-3.196527'],
      'Plymouth Centre': ['50.371670', '-4.142361'],
      'Plymouth Tavistock Road.': ['50.411058', '-4.130288'],
      'Port Talbot Margam': ['51.583950', '-3.770822'],
      'Portsmouth': ['50.828810', '-1.068583'],
      'Preston': ['53.765590', '-2.680353'],
      'Reading London Road': ['51.454896', '-0.940382'],
      'Reading New Town': ['51.453090', '-0.944067'],
      'Rochester Stoke': ['51.456170', '0.634889'],
      'Salford Eccles': ['53.484810', '-2.334139'],
      'Sandy Roadside': ['52.132417', '-0.300306'],
      'Scunthorpe Town': ['53.586340', '-0.636811'],
      'Shaw Crompton Way': ['53.579283', '-2.093786'],
      'Sheffield Barnsley Road': ['53.404950', '-1.455815'],
      'Sheffield Devonshire Green': ['53.378622', '-1.478096'],
      'Sheffield Tinsley': ['53.410580', '-1.396139'],
      'Southampton A33': ['50.920265', '-1.463484'],
      'Southampton Centre': ['50.908140', '-1.395778'],
      'Southend-on-Sea': ['51.544206', '0.678408'],
      'St Helens Linkway': ['53.451826', '-2.742134'],
      'St Osyth': ['51.777980', '1.049031'],
      'Stanford-le-Hope Roadside': ['51.518167', '0.439548'],
      'Stockton-on-Tees Eaglescliffe': ['54.516667', '-1.358547'],
      'Stoke-on-Trent A50 Roadside': ['52.980436', '-2.111898'],
      'Stoke-on-Trent Centre': ['53.028210', '-2.175133'],
      'Sunderland Silksworth': ['54.883610', '-1.406878'],
      'Sunderland Wessington Way': ['54.918390', '-1.408391'],
      'Swansea Roadside': ['51.632696', '-3.947374'],
      'Thurrock': ['51.477070', '0.317969'],
      'Walsall Woodlands': ['52.605621', '-2.030523'],
      'Warrington': ['53.389280', '-2.615358'],
      'Wicken Fen': ['52.298500', '0.290917'],
      'Widnes Milton Road': ['53.365391', '-2.731680'],
      'Wigan Centre': ['53.549140', '-2.638139'],
      'Wirral Tranmere': ['53.372870', '-3.022722'],
      'Worthing A27 Roadside': ['50.832947', '-0.379916'],
      'Wrexham': ['53.042220', '-3.002778'],
      'Yarner Wood': ['50.597600', '-3.716510'],
      'York Bootham': ['53.967513', '-1.086514'],
      'York Fishergate': ['53.951889', '-1.075861']
     }

def get_info(site):
    url = site_urls.get(site)
    lat = site_geo.get(site)[0]
    long = site_geo.get(site)[1]
    return [site, url, lat, long]

site_urls = {'Aberdeen': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ABD',
     'Aberdeen Union Street Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ABD7',
     'Aberdeen Wellington Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ABD8',
     'Armagh Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ARM6',
     'Aston Hill': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=AH',
     'Auchencorth Moss': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ACTH',
     'Ballymena Antrim Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BAAR',
     'Ballymena Ballykeel': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BALM',
     'Barnsley Gawber': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BAR3',
     'Barnstaple A39': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BPLE',
     'Bath Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BATH',
     'Belfast Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BEL2',
     "Belfast Stockman's Lane": 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BEL1',
     'Billingham': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BIL',
     'Birkenhead Borough Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BBRD',
     'Birmingham A4540 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BIRR',
     'Birmingham Acocks Green': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=AGRN',
     'Blackburn Accrington Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BLAR',
     'Blackpool Marton': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BLC2',
     'Bournemouth': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BORN',
     'Bradford Mayo Avenue': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BDMA',
     'Brighton Preston Park': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BRT3',
     "Bristol St Paul's": 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BRS8',
     'Bristol Temple Way': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BR11',
     'Bury Whitefield Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BURW',
     'Bush Estate': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BUSH',
     'Cambridge Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CAM',
     'Camden Kerbside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CA1',
     'Cannock A5190 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CANK',
     'Canterbury': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CANT',
     'Cardiff Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CARD',
     'Carlisle Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CARL',
     'Charlton Mackrell': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MACK',
     'Chatham Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CHAT',
     'Chepstow A48': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CHP',
     'Chesterfield Loundsley Green': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CHLG',
     'Chesterfield Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CHS7',
     'Chilbolton Observatory': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CHBO',
     'Christchurch Barrack Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CHBR',
     'Coventry Allesley': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=COAL',
     'Coventry Binley Road.': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=COBR',
     'Cwmbran': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CWMB',
     "Derby St Alkmund's Way": 'https://uk-air.defra.gov.uk/networks/site-info?site_id=DESA',
     'Derry Rosemount': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=DERR',
     'Doncaster A630 Cleveland Street': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=DCST',
     'Dumbarton Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=DUMB',
     'Dumfries': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=DUMF',
     'Ealing Horn Lane': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=EA8',
     'Eastbourne': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=EB',
     'Edinburgh St Leonards': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ED3',
     'Eskdalemuir': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ESK',
     'Exeter Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=EX',
     'Fort William': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=FW',
     'Glasgow Great Western Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GGWR',
     'Glasgow High Street': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GHSR',
     'Glasgow Kerbside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GLA4',
     'Glasgow Townhead': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GLKP',
     'Glazebury': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GLAZ',
     'Grangemouth': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GRAN',
     'Grangemouth Moray': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GRA2',
     'Greenock A8 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=GKA8',
     'Hafod-yr-ynys Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CAE6',
     'Haringey Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HG1',
     'High Muffles': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HM',
     'Honiton': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HONI',
     'Horley': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HORE',
     'Hull Freetown': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HUL2',
     'Hull Holderness Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HULR',
     'Inverness': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=INV2',
     'Ladybower': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LB',
     'Leamington Spa': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LEAM',
     'Leamington Spa Rugby Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LEAR',
     'Leeds Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LEED',
     'Leeds Headingley Kerbside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LED6',
     'Leicester A594 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LEIR',
     'Leicester University': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LECU',
     'Leominster': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LEOM',
     'Lerwick': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LERW',
     'Lincoln Canwick Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LIN3',
     'Liverpool Speke': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LVP',
     'London Bexley': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BEX',
     'London Bloomsbury': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CLL2',
     'London Eltham': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LON6',
     'London Haringey Priory Park South': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HG4',
     'London Harlington': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HRL',
     'London Harrow Stanmore': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HR3',
     'London Hillingdon': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HIL',
     'London Marylebone Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MY1',
     'London N. Kensington': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=KC1',
     'London Teddington Bushy Park': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=TED2',
     'London Westminster': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HORS',
     'Lough Navar': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LN',
     'Lullington Heath': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LH',
     'Luton A505 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=LUTR',
     'Mace Head': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MH',
     'Manchester Piccadilly': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MAN3',
     'Manchester Sharston': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MAHG',
     'Market Harborough': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MKTH',
     'Middlesbrough': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=MID',
     'Narberth': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PEMB',
     'Newcastle Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NEWC',
     'Newcastle Cradlewell Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NCA3',
     'Newport': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NPT3',
     'Northampton Spring Park': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NTN4',
     'Norwich Lakenfields': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NO12',
     'Nottingham Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NOTT',
     'Nottingham Western Boulevard': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=NWBV',
     'Oldbury Birmingham Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=BOLD',
     'Oxford Centre Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=OX',
     'Oxford St Ebbes': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=OX8',
     'Peebles': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PEEB',
     'Plymouth Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PLYM',
     'Plymouth Tavistock Road.': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PLYR',
     'Port Talbot Margam': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PT4',
     'Portsmouth': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PMTH',
     'Preston': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=PRES',
     'Reading London Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=REA5',
     'Reading New Town': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=REA1',
     'Rochester Stoke': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ROCH',
     'Salford Eccles': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=ECCL',
     'Saltash Callington Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SASH',
     'Sandy Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SDY',
     'Scunthorpe Town': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SCN2',
     'Shaw Crompton Way': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=CW',
     'Sheffield Barnsley Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SHBR',
     'Sheffield Devonshire Green': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SHDG',
     'Sheffield Tinsley': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SHE',
     'Sibton': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SIB',
     'Southampton A33': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SA33',
     'Southampton Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SOUT',
     'Southend-on-Sea': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SEND',
     'Southwark A2 Old Kent Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SK5',
     'St Helens Linkway': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SHLW',
     'St Osyth': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=OSY',
     'Stanford-le-Hope Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=HOPE',
     'Stockton-on-Tees A1305 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SOTR',
     'Stockton-on-Tees Eaglescliffe': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=EAGL',
     'Stoke-on-Trent A50 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=STKR',
     'Stoke-on-Trent Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=STOK',
     'Storrington Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=STOR',
     'Strathvaich': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SV',
     'Sunderland Silksworth': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SUN2',
     'Sunderland Wessington Way': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SUNR',
     'Swansea Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=SWA1',
     'Thurrock': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=THUR',
     'Tower Hamlets Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=TH2',
     'Walsall Woodlands': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WAL4',
     'Warrington': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WAR',
     'Weybourne': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WEYB',
     'Wicken Fen': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WFEN',
     'Widnes Milton Road': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WSMR',
     'Wigan Centre': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WIG5',
     'Wirral Tranmere': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=TRAN',
     'Worthing A27 Roadside': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WTHG',
     'Wrexham': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=WREX',
     'Yarner Wood': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=YW',
     'York Bootham': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=YK10',
     'York Fishergate': 'https://uk-air.defra.gov.uk/networks/site-info?site_id=YK11'}

site_list = [
     'Aberdeen',
     'Aberdeen Union Street Roadside',
     'Aberdeen Wellington Road',
     'Armagh Roadside',
     'Aston Hill',
     'Auchencorth Moss',
     'Barnsley Gawber',
     'Barnstaple A39',
     'Bath Roadside',
     'Belfast Centre',
     "Belfast Stockman's Lane",
     'Birkenhead Borough Road',
     'Birmingham A4540 Roadside',
     'Birmingham Acocks Green',
     'Blackpool Marton',
     'Bournemouth',
     'Bradford Mayo Avenue',
     'Brighton Preston Park',
     "Bristol St Paul's",
     'Bristol Temple Way',
     'Bury Whitefield Roadside',
     'Cambridge Roadside',
     'Camden Kerbside',
     'Cannock A5190 Roadside',
     'Canterbury',
     'Cardiff Centre',
     'Carlisle Roadside',
     'Charlton Mackrell',
     'Chatham Roadside',
     'Chepstow A48',
     'Chesterfield Loundsley Green',
     'Chesterfield Roadside',
     'Chilbolton Observatory',
     'Christchurch Barrack Road',
     'Coventry Allesley',
     'Coventry Binley Road.',
     'Cwmbran',
     "Derby St Alkmund's Way",
     'Doncaster A630 Cleveland Street',
     'Eastbourne',
     'Edinburgh St Leonards',
     'Eskdalemuir',
     'Exeter Roadside',
     'Fort William',
     'Glasgow High Street',
     'Glazebury',
     'Grangemouth',
     'Grangemouth Moray',
     'High Muffles',
     'Horley',
     'Hull Freetown',
     'Hull Holderness Road',
     'Inverness',
     'Ladybower',
     'Leamington Spa',
     'Leamington Spa Rugby Road',
     'Leeds Centre',
     'Leeds Headingley Kerbside',
     'Leicester A594 Roadside',
     'Leicester University',
     'Leominster',
     'Liverpool Speke',
     'London Bexley',
     'London Bloomsbury',
     'London Eltham',
     'London Harlington',
     'London Marylebone Road',
     'London N. Kensington',
     'London Westminster',
     'Lullington Heath',
     'Luton A505 Roadside',
     'Manchester Piccadilly',
     'Manchester Sharston',
     'Middlesbrough',
     'Narberth',
     'Newcastle Centre',
     'Newport',
     'Norwich Lakenfields',
     'Nottingham Centre',
     'Nottingham Western Boulevard',
     'Oldbury Birmingham Road',
     'Oxford Centre Roadside',
     'Oxford St Ebbes',
     'Peebles',
     'Plymouth Centre',
     'Plymouth Tavistock Road.',
     'Port Talbot Margam',
     'Portsmouth',
     'Preston',
     'Reading London Road',
     'Reading New Town',
     'Rochester Stoke',
     'Salford Eccles',
     'Sandy Roadside',
     'Scunthorpe Town',
     'Shaw Crompton Way',
     'Sheffield Barnsley Road',
     'Sheffield Devonshire Green',
     'Sheffield Tinsley',
     'Southampton A33',
     'Southampton Centre',
     'Southend-on-Sea',
     'St Helens Linkway',
     'St Osyth',
     'Stanford-le-Hope Roadside',
     'Stockton-on-Tees Eaglescliffe',
     'Stoke-on-Trent A50 Roadside',
     'Stoke-on-Trent Centre',
     'Sunderland Silksworth',
     'Sunderland Wessington Way',
     'Swansea Roadside',
     'Thurrock',
     'Walsall Woodlands',
     'Warrington',
     'Wicken Fen',
     'Widnes Milton Road',
     'Wigan Centre',
     'Wirral Tranmere',
     'Worthing A27 Roadside',
     'Wrexham',
     'Yarner Wood',
     'York Bootham',
     'York Fishergate'
]