no2_site_list = [
    'Edinburgh St Leonards',
    'Glasgow High Street',
    'Grangemouth',
    'Grangemouth Moray',
    'Chesterfield Loundsley Green',
    'Chesterfield Roadside',
    "Derby St Alkmund's Way",
    'Ladybower',
    'Leicester A594 Roadside',
    'Leicester University',
    'Nottingham Centre',
    'Nottingham Western Boulevard',
    'Cambridge Roadside',
    'Luton A505 Roadside',
    'Norwich Lakenfields',
    'Sandy Roadside',
    'Southend-on-Sea',
    'St Osyth',
    'Stanford-le-Hope Roadside',
    'Thurrock',
    'Wicken Fen',
    'Camden Kerbside',
    'London Bexley',
    'London Bloomsbury',
    'London Eltham',
    'London Harlington',
    'London Marylebone Road',
    'London N. Kensington',
    'London Westminster',
    'Fort William',
    'Inverness',
    'Middlesbrough',
    'Newcastle Centre',
    'Stockton-on-Tees Eaglescliffe',
    'Sunderland Silksworth',
    'Sunderland Wessington Way',
    'Aberdeen',
    'Aberdeen Union Street Roadside',
    'Aberdeen Wellington Road',
    'Aston Hill',
    'Wrexham',
    'Birkenhead Borough Road',
    'Blackpool Marton',
    'Bury Whitefield Roadside',
    'Carlisle Roadside',
    'Glazebury',
    'Liverpool Speke',
    'Manchester Piccadilly',
    'Manchester Sharston',
    'Preston',
    'Salford Eccles',
    'Shaw Crompton Way',
    'St Helens Linkway',
    'Warrington',
    'Widnes Milton Road',
    'Wigan Centre',
    'Wirral Tranmere',
    'Armagh Roadside',
    'Belfast Centre',
    "Belfast Stockman's Lane",
    'Eskdalemuir',
    'Peebles',
    'Brighton Preston Park',
    'Canterbury',
    'Chatham Roadside',
    'Chilbolton Observatory',
    'Eastbourne',
    'Horley',
    'Lullington Heath',
    'Oxford Centre Roadside',
    'Oxford St Ebbes',
    'Portsmouth',
    'Reading London Road',
    'Reading New Town',
    'Rochester Stoke',
    'Southampton A33',
    'Southampton Centre',
    'Worthing A27 Roadside',
    'Cardiff Centre',
    'Chepstow A48',
    'Cwmbran',
    'Narberth',
    'Newport',
    'Port Talbot Margam',
    'Swansea Roadside',
    'Bath Roadside',
    'Bournemouth',
    "Bristol St Paul's",
    'Bristol Temple Way',
    'Charlton Mackrell',
    'Christchurch Barrack Road',
    'Exeter Roadside',
    'Plymouth Centre',
    'Plymouth Tavistock Road.',
    'Yarner Wood',
    'Birmingham A4540 Roadside',
    'Birmingham Acocks Green',
    'Cannock A5190 Roadside',
    'Coventry Allesley',
    'Coventry Binley Road.',
    'Leamington Spa',
    'Leamington Spa Rugby Road',
    'Leominster',
    'Oldbury Birmingham Road',
    'Stoke-on-Trent A50 Roadside',
    'Stoke-on-Trent Centre',
    'Walsall Woodlands',
    'Barnsley Gawber',
    'Bradford Mayo Avenue',
    'Doncaster A630 Cleveland Street',
    'High Muffles',
    'Hull Freetown',
    'Hull Holderness Road',
    'Leeds Centre',
    'Leeds Headingley Kerbside',
    'Scunthorpe Town',
    'Sheffield Barnsley Road',
    'Sheffield Devonshire Green',
    'Sheffield Tinsley',
    'York Bootham',
    'York Fishergate'
]

pm_site_list = [
    'Auchencorth Moss',
    'Edinburgh St Leonards',
    'Glasgow High Street',
    'Grangemouth',
    'Chesterfield Loundsley Green',
    'Chesterfield Roadside',
    'Leicester A594 Roadside',
    'Leicester University',
    'Nottingham Centre',
    'Nottingham Western Boulevard',
    'Norwich Lakenfields',
    'Southend-on-Sea',
    'Thurrock',
    'Camden Kerbside',
    'London Bexley',
    'London Bloomsbury',
    'London Marylebone Road',
    'London N. Kensington',
    'Middlesbrough',
    'Newcastle Centre',
    'Stockton-on-Tees Eaglescliffe',
    'Sunderland Silksworth',
    'Blackpool Marton',
    'Bury Whitefield Roadside',
    'Carlisle Roadside',
    'Liverpool Speke',
    'Manchester Piccadilly',
    'Preston',
    'Salford Eccles',
    'St Helens Linkway',
    'Warrington',
    'Wigan Centre',
    'Wirral Tranmere',
    'Armagh Roadside',
    'Belfast Centre',
    "Belfast Stockman's Lane",
    'Chatham Roadside',
    'Chilbolton Observatory',
    'Eastbourne',
    'Oxford St Ebbes',
    'Portsmouth',
    'Reading London Road',
    'Reading New Town',
    'Rochester Stoke',
    'Southampton A33',
    'Southampton Centre',
    'Cardiff Centre',
    'Chepstow A48',
    'Port Talbot Margam',
    'Barnstaple A39',
    "Bristol St Paul's",
    'Plymouth Centre',
    'Birmingham A4540 Roadside',
    'Coventry Binley Road.',
    'Leamington Spa',
    'Leamington Spa Rugby Road',
    'Stoke-on-Trent A50 Roadside',
    'Stoke-on-Trent Centre',
    'Hull Freetown',
    'Hull Holderness Road',
    'Leeds Centre',
    'Leeds Headingley Kerbside',
    'Scunthorpe Town',
    'Sheffield Devonshire Green',
    'York Bootham',
    'York Fishergate'
]
