all_sites = [
     'Aberdeen',
     'Aberdeen Union Street Roadside',
     'Aberdeen Wellington Road',
     'Armagh Roadside',
     'Aston Hill',
     'Auchencorth Moss',
     'Barnsley Gawber',
     'Barnstaple A39',
     'Bath Roadside',
     'Belfast Centre',
     "Belfast Stockman's Lane",
     'Birkenhead Borough Road',
     'Birmingham A4540 Roadside',
     'Birmingham Acocks Green',
     'Blackpool Marton',
     'Bournemouth',
     'Bradford Mayo Avenue',
     'Brighton Preston Park',
     "Bristol St Paul's",
     'Bristol Temple Way',
     'Bury Whitefield Roadside',
     'Cambridge Roadside',
     'Camden Kerbside',
     'Cannock A5190 Roadside',
     'Canterbury',
     'Cardiff Centre',
     'Carlisle Roadside',
     'Charlton Mackrell',
     'Chatham Roadside',
     'Chepstow A48',
     'Chesterfield Loundsley Green',
     'Chesterfield Roadside',
     'Chilbolton Observatory',
     'Christchurch Barrack Road',
     'Coventry Allesley',
     'Coventry Binley Road.',
     'Cwmbran',
     "Derby St Alkmund's Way",
     'Doncaster A630 Cleveland Street',
     'Eastbourne',
     'Edinburgh St Leonards',
     'Eskdalemuir',
     'Exeter Roadside',
     'Fort William',
     'Glasgow High Street',
     'Glazebury',
     'Grangemouth',
     'Grangemouth Moray',
     'High Muffles',
     'Horley',
     'Hull Freetown',
     'Hull Holderness Road',
     'Inverness',
     'Ladybower',
     'Leamington Spa',
     'Leamington Spa Rugby Road',
     'Leeds Centre',
     'Leeds Headingley Kerbside',
     'Leicester A594 Roadside',
     'Leicester University',
     'Leominster',
     'Liverpool Speke',
     'London Bexley',
     'London Bloomsbury',
     'London Eltham',
     'London Harlington',
     'London Marylebone Road',
     'London N. Kensington',
     'London Westminster',
     'Lullington Heath',
     'Luton A505 Roadside',
     'Manchester Piccadilly',
     'Manchester Sharston',
     'Middlesbrough',
     'Narberth',
     'Newcastle Centre',
     'Newport',
     'Norwich Lakenfields',
     'Nottingham Centre',
     'Nottingham Western Boulevard',
     'Oldbury Birmingham Road',
     'Oxford Centre Roadside',
     'Oxford St Ebbes',
     'Peebles',
     'Plymouth Centre',
     'Plymouth Tavistock Road.',
     'Port Talbot Margam',
     'Portsmouth',
     'Preston',
     'Reading London Road',
     'Reading New Town',
     'Rochester Stoke',
     'Salford Eccles',
     'Sandy Roadside',
     'Scunthorpe Town',
     'Shaw Crompton Way',
     'Sheffield Barnsley Road',
     'Sheffield Devonshire Green',
     'Sheffield Tinsley',
     'Southampton A33',
     'Southampton Centre',
     'Southend-on-Sea',
     'St Helens Linkway',
     'St Osyth',
     'Stanford-le-Hope Roadside',
     'Stockton-on-Tees Eaglescliffe',
     'Stoke-on-Trent A50 Roadside',
     'Stoke-on-Trent Centre',
     'Sunderland Silksworth',
     'Sunderland Wessington Way',
     'Swansea Roadside',
     'Thurrock',
     'Walsall Woodlands',
     'Warrington',
     'Wicken Fen',
     'Widnes Milton Road',
     'Wigan Centre',
     'Wirral Tranmere',
     'Worthing A27 Roadside',
     'Wrexham',
     'Yarner Wood',
     'York Bootham',
     'York Fishergate'
]

"""site_id=ABD

    'Aberdeen',    site_id=ABD
     'Aberdeen Union Street Roadside',
     'Aberdeen Wellington Road',
     'Armagh Roadside',
     'Aston Hill',
     'Auchencorth Moss',
     'Barnsley Gawber',
     'Barnstaple A39',
     'Bath Roadside',
     'Belfast Centre',
     "Belfast Stockman's Lane",
     'Birkenhead Borough Road',
     'Birmingham A4540 Roadside',
     'Birmingham Acocks Green',
     'Blackpool Marton',
     'Bournemouth',
     'Bradford Mayo Avenue',
     'Brighton Preston Park',
     "Bristol St Paul's",
     'Bristol Temple Way',
     'Bury Whitefield Roadside',
     'Cambridge Roadside',
     'Camden Kerbside',
     'Cannock A5190 Roadside',
     'Canterbury',
     'Cardiff Centre',
     'Carlisle Roadside',
     'Charlton Mackrell',
     'Chatham Roadside',
     'Chepstow A48',
     'Chesterfield Loundsley Green',
     'Chesterfield Roadside',
     'Chilbolton Observatory',
     'Christchurch Barrack Road',
     'Coventry Allesley',
     'Coventry Binley Road.',
     'Cwmbran',
     "Derby St Alkmund's Way",
     'Doncaster A630 Cleveland Street',
     'Eastbourne',
     'Edinburgh St Leonards',
     'Eskdalemuir',
     'Exeter Roadside',
     'Fort William',
     'Glasgow High Street',
     'Glazebury',
     'Grangemouth',
     'Grangemouth Moray',
     'High Muffles',
     'Horley',
     'Hull Freetown',
     'Hull Holderness Road',
     'Inverness',
     'Ladybower',
     'Leamington Spa',
     'Leamington Spa Rugby Road',
     'Leeds Centre',
     'Leeds Headingley Kerbside',
     'Leicester A594 Roadside',
     'Leicester University',
     'Leominster',
     'Liverpool Speke',
     'London Bexley',
     'London Bloomsbury',
     'London Eltham',
     'London Harlington',
     'London Marylebone Road',
     'London N. Kensington',
     'London Westminster',
     'Lullington Heath',
     'Luton A505 Roadside',
     'Manchester Piccadilly',
     'Manchester Sharston',
     'Middlesbrough',
     'Narberth',
     'Newcastle Centre',
     'Newport',
     'Norwich Lakenfields',
     'Nottingham Centre',
     'Nottingham Western Boulevard',
     'Oldbury Birmingham Road',
     'Oxford Centre Roadside',
     'Oxford St Ebbes',
     'Peebles',
     'Plymouth Centre',
     'Plymouth Tavistock Road.',
     'Port Talbot Margam',
     'Portsmouth',
     'Preston',
     'Reading London Road',
     'Reading New Town',
     'Rochester Stoke',
     'Salford Eccles',
     'Sandy Roadside',
     'Scunthorpe Town',
     'Shaw Crompton Way',
     'Sheffield Barnsley Road',
     'Sheffield Devonshire Green',
     'Sheffield Tinsley',
     'Southampton A33',
     'Southampton Centre',
     'Southend-on-Sea',
     'St Helens Linkway',
     'St Osyth',
     'Stanford-le-Hope Roadside',
     'Stockton-on-Tees Eaglescliffe',
     'Stoke-on-Trent A50 Roadside',
     'Stoke-on-Trent Centre',
     'Sunderland Silksworth',
     'Sunderland Wessington Way',
     'Swansea Roadside',
     'Thurrock',
     'Walsall Woodlands',
     'Warrington',
     'Wicken Fen',
     'Widnes Milton Road',
     'Wigan Centre',
     'Wirral Tranmere',
     'Worthing A27 Roadside',
     'Wrexham',
     'Yarner Wood',
     'York Bootham',
     'York Fishergate'

no2_site_list = [
    'Edinburgh St Leonards',
    'Glasgow High Street',
    'Grangemouth',
    'Grangemouth Moray',
    'Chesterfield Loundsley Green',
    'Chesterfield Roadside',
    "Derby St Alkmund's Way",
    'Ladybower',
    'Leicester A594 Roadside',
    'Leicester University',
    'Nottingham Centre',
    'Nottingham Western Boulevard',
    'Cambridge Roadside',
    'Luton A505 Roadside',
    'Norwich Lakenfields',
    'Sandy Roadside',
    'Southend-on-Sea',
    'St Osyth',
    'Stanford-le-Hope Roadside',
    'Thurrock',
    'Wicken Fen',
    'Camden Kerbside',
    'London Bexley',
    'London Bloomsbury',
    'London Eltham',
    'London Harlington',
    'London Marylebone Road',
    'London N. Kensington',
    'London Westminster',
    'Fort William',
    'Inverness',
    'Middlesbrough',
    'Newcastle Centre',
    'Stockton-on-Tees Eaglescliffe',
    'Sunderland Silksworth',
    'Sunderland Wessington Way',
    'Aberdeen',
    'Aberdeen Union Street Roadside',
    'Aberdeen Wellington Road',
    'Aston Hill',
    'Wrexham',
    'Birkenhead Borough Road',
    'Blackpool Marton',
    'Bury Whitefield Roadside',
    'Carlisle Roadside',
    'Glazebury',
    'Liverpool Speke',
    'Manchester Piccadilly',
    'Manchester Sharston',
    'Preston',
    'Salford Eccles',
    'Shaw Crompton Way',
    'St Helens Linkway',
    'Warrington',
    'Widnes Milton Road',
    'Wigan Centre',
    'Wirral Tranmere',
    'Armagh Roadside',
    'Belfast Centre',
    "Belfast Stockman's Lane",
    'Eskdalemuir',
    'Peebles',
    'Brighton Preston Park',
    'Canterbury',
    'Chatham Roadside',
    'Chilbolton Observatory',
    'Eastbourne',
    'Horley',
    'Lullington Heath',
    'Oxford Centre Roadside',
    'Oxford St Ebbes',
    'Portsmouth',
    'Reading London Road',
    'Reading New Town',
    'Rochester Stoke',
    'Southampton A33',
    'Southampton Centre',
    'Worthing A27 Roadside',
    'Cardiff Centre',
    'Chepstow A48',
    'Cwmbran',
    'Narberth',
    'Newport',
    'Port Talbot Margam',
    'Swansea Roadside',
    'Bath Roadside',
    'Bournemouth',
    "Bristol St Paul's",
    'Bristol Temple Way',
    'Charlton Mackrell',
    'Christchurch Barrack Road',
    'Exeter Roadside',
    'Plymouth Centre',
    'Plymouth Tavistock Road.',
    'Yarner Wood',
    'Birmingham A4540 Roadside',
    'Birmingham Acocks Green',
    'Cannock A5190 Roadside',
    'Coventry Allesley',
    'Coventry Binley Road.',
    'Leamington Spa',
    'Leamington Spa Rugby Road',
    'Leominster',
    'Oldbury Birmingham Road',
    'Stoke-on-Trent A50 Roadside',
    'Stoke-on-Trent Centre',
    'Walsall Woodlands',
    'Barnsley Gawber',
    'Bradford Mayo Avenue',
    'Doncaster A630 Cleveland Street',
    'High Muffles',
    'Hull Freetown',
    'Hull Holderness Road',
    'Leeds Centre',
    'Leeds Headingley Kerbside',
    'Scunthorpe Town',
    'Sheffield Barnsley Road',
    'Sheffield Devonshire Green',
    'Sheffield Tinsley',
    'York Bootham',
    'York Fishergate'
]

pm_site_list = [
    'Auchencorth Moss',
    'Edinburgh St Leonards',
    'Glasgow High Street',
    'Grangemouth',
    'Chesterfield Loundsley Green',
    'Chesterfield Roadside',
    'Leicester A594 Roadside',
    'Leicester University',
    'Nottingham Centre',
    'Nottingham Western Boulevard',
    'Norwich Lakenfields',
    'Southend-on-Sea',
    'Thurrock',
    'Camden Kerbside',
    'London Bexley',
    'London Bloomsbury',
    'London Marylebone Road',
    'London N. Kensington',
    'Middlesbrough',
    'Newcastle Centre',
    'Stockton-on-Tees Eaglescliffe',
    'Sunderland Silksworth',
    'Blackpool Marton',
    'Bury Whitefield Roadside',
    'Carlisle Roadside',
    'Liverpool Speke',
    'Manchester Piccadilly',
    'Preston',
    'Salford Eccles',
    'St Helens Linkway',
    'Warrington',
    'Wigan Centre',
    'Wirral Tranmere',
    'Armagh Roadside',
    'Belfast Centre',
    "Belfast Stockman's Lane",
    'Chatham Roadside',
    'Chilbolton Observatory',
    'Eastbourne',
    'Oxford St Ebbes',
    'Portsmouth',
    'Reading London Road',
    'Reading New Town',
    'Rochester Stoke',
    'Southampton A33',
    'Southampton Centre',
    'Cardiff Centre',
    'Chepstow A48',
    'Port Talbot Margam',
    'Barnstaple A39',
    "Bristol St Paul's",
    'Plymouth Centre',
    'Birmingham A4540 Roadside',
    'Coventry Binley Road.',
    'Leamington Spa',
    'Leamington Spa Rugby Road',
    'Stoke-on-Trent A50 Roadside',
    'Stoke-on-Trent Centre',
    'Hull Freetown',
    'Hull Holderness Road',
    'Leeds Centre',
    'Leeds Headingley Kerbside',
    'Scunthorpe Town',
    'Sheffield Devonshire Green',
    'York Bootham',
    'York Fishergate'
]

"""
